name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run dev --if-present
    - run: npm start
    - name: publish
      env:
        CI: true
        super_secret: ${{ secrets.TEST_KEY }} 
      run: |
        echo 'printing secret key'
        echo $TEST_KEY
        echo $super_secret
